# Stop-DockerContainers.ps1
# Graceful Container Termination System
# Implements graceful shutdown sequence for Docker containers
# Includes timeout handling and verification of clean shutdown

<#
.SYNOPSIS
    Gracefully terminates Docker containers during migration.

.DESCRIPTION
    Implements a graceful shutdown sequence for Docker containers with configurable
    timeout handling. Verifies that containers stopped cleanly before proceeding.
    Integrates with migration state tracking for audit and rollback capability.

.PARAMETER InventoryPath
    Path to the inventory JSON file generated by Get-DockerInventory.ps1
    Default: C:\project\migration\inventory.json

.PARAMETER StatePath
    Path to the migration state JSON file.
    Default: C:\project\migration\migration-state.json

.PARAMETER GracefulTimeout
    Timeout in seconds for graceful shutdown (docker stop).
    Default: 30 seconds

.PARAMETER ForceTimeout
    Additional timeout in seconds before forcing kill if graceful shutdown fails.
    Default: 10 seconds

.PARAMETER VerifyCleanShutdown
    Verify that containers are fully stopped and removed.
    Default: $true

.EXAMPLE
    .\Stop-DockerContainers.ps1
    Stops all containers from default inventory with default timeouts.

.EXAMPLE
    .\Stop-DockerContainers.ps1 -GracefulTimeout 60 -ForceTimeout 15
    Stops containers with custom timeout values.

.EXAMPLE
    .\Stop-DockerContainers.ps1 -InventoryPath "C:\custom\inventory.json"
    Stops containers using custom inventory path.

.NOTES
    Validates: Requirements 1.2
    Part of: Sentient Corp Native Architecture Migration
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$InventoryPath = "C:\project\migration\inventory.json",
    
    [Parameter(Mandatory=$false)]
    [string]$StatePath = "C:\project\migration\migration-state.json",
    
    [Parameter(Mandatory=$false)]
    [int]$GracefulTimeout = 30,
    
    [Parameter(Mandatory=$false)]
    [int]$ForceTimeout = 10,
    
    [Parameter(Mandatory=$false)]
    [bool]$VerifyCleanShutdown = $true
)

$ErrorActionPreference = "Stop"

# Import MigrationState functions
$migrationStateScript = Join-Path $PSScriptRoot "MigrationState.ps1"
if (Test-Path $migrationStateScript) {
    . $migrationStateScript
}
else {
    Write-Warning "MigrationState.ps1 not found. State tracking will be limited."
}

# Initialize termination report
$terminationReport = @{
    started_at = Get-Date -Format "o"
    completed_at = $null
    inventory_source = $InventoryPath
    containers = @()
    summary = @{
        total_containers = 0
        successfully_stopped = 0
        failed_to_stop = 0
        forcefully_killed = 0
        verification_passed = $false
    }
}

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message"
}

function Test-ContainerRunning {
    <#
    .SYNOPSIS
        Checks if a container is currently running.
    
    .PARAMETER ContainerId
        The container ID to check.
    
    .RETURNS
        $true if container is running, $false otherwise.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$ContainerId
    )
    
    try {
        $status = docker inspect --format='{{.State.Running}}' $ContainerId 2>&1
        
        if ($LASTEXITCODE -ne 0) {
            Write-Log "Container $ContainerId not found or error checking status" "WARNING"
            return $false
        }
        
        return $status -eq "true"
    }
    catch {
        Write-Log "Error checking container status: $_" "WARNING"
        return $false
    }
}

function Test-ContainerExists {
    <#
    .SYNOPSIS
        Checks if a container exists (running or stopped).
    
    .PARAMETER ContainerId
        The container ID to check.
    
    .RETURNS
        $true if container exists, $false otherwise.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$ContainerId
    )
    
    try {
        $null = docker inspect $ContainerId 2>&1
        return $LASTEXITCODE -eq 0
    }
    catch {
        return $false
    }
}

function Stop-ContainerGracefully {
    <#
    .SYNOPSIS
        Attempts graceful shutdown of a container.
    
    .PARAMETER ContainerId
        The container ID to stop.
    
    .PARAMETER ContainerName
        The container name (for logging).
    
    .PARAMETER Timeout
        Timeout in seconds for graceful shutdown.
    
    .RETURNS
        Hashtable with success status and details.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$ContainerId,
        
        [Parameter(Mandatory=$true)]
        [string]$ContainerName,
        
        [Parameter(Mandatory=$true)]
        [int]$Timeout
    )
    
    try {
        Write-Log "Attempting graceful shutdown of container: $ContainerName (timeout: ${Timeout}s)" "INFO"
        
        $result = @{
            container_id = $ContainerId
            container_name = $ContainerName
            method = "graceful"
            success = $false
            stopped_at = $null
            error = $null
            duration_seconds = 0
        }
        
        # Check if container is running
        if (-not (Test-ContainerRunning -ContainerId $ContainerId)) {
            Write-Log "Container $ContainerName is not running" "INFO"
            $result.success = $true
            $result.stopped_at = Get-Date -Format "o"
            return $result
        }
        
        # Record start time
        $startTime = Get-Date
        
        # Execute docker stop with timeout
        Write-Log "Executing: docker stop --time $Timeout $ContainerId" "INFO"
        $stopOutput = docker stop --time $Timeout $ContainerId 2>&1
        
        # Record duration
        $endTime = Get-Date
        $result.duration_seconds = [math]::Round(($endTime - $startTime).TotalSeconds, 2)
        
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Container $ContainerName stopped gracefully in $($result.duration_seconds)s" "INFO"
            $result.success = $true
            $result.stopped_at = Get-Date -Format "o"
        }
        else {
            Write-Log "Failed to stop container $ContainerName : $stopOutput" "ERROR"
            $result.error = "Docker stop failed: $stopOutput"
        }
        
        return $result
    }
    catch {
        Write-Log "Exception during graceful shutdown of $ContainerName : $_" "ERROR"
        return @{
            container_id = $ContainerId
            container_name = $ContainerName
            method = "graceful"
            success = $false
            error = $_.Exception.Message
        }
    }
}

function Stop-ContainerForcefully {
    <#
    .SYNOPSIS
        Forcefully kills a container.
    
    .PARAMETER ContainerId
        The container ID to kill.
    
    .PARAMETER ContainerName
        The container name (for logging).
    
    .RETURNS
        Hashtable with success status and details.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [string]$ContainerId,
        
        [Parameter(Mandatory=$true)]
        [string]$ContainerName
    )
    
    try {
        Write-Log "Forcefully killing container: $ContainerName" "WARNING"
        
        $result = @{
            container_id = $ContainerId
            container_name = $ContainerName
            method = "force"
            success = $false
            stopped_at = $null
            error = $null
        }
        
        # Execute docker kill
        Write-Log "Executing: docker kill $ContainerId" "INFO"
        $killOutput = docker kill $ContainerId 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Container $ContainerName killed forcefully" "WARNING"
            $result.success = $true
            $result.stopped_at = Get-Date -Format "o"
            $terminationReport.summary.forcefully_killed++
        }
        else {
            Write-Log "Failed to kill container $ContainerName : $killOutput" "ERROR"
            $result.error = "Docker kill failed: $killOutput"
        }
        
        return $result
    }
    catch {
        Write-Log "Exception during forceful kill of $ContainerName : $_" "ERROR"
        return @{
            container_id = $ContainerId
            container_name = $ContainerName
            method = "force"
            success = $false
            error = $_.Exception.Message
        }
    }
}

function Stop-Container {
    <#
    .SYNOPSIS
        Stops a container with graceful shutdown and force fallback.
    
    .PARAMETER ContainerMetadata
        Container metadata from inventory.
    
    .PARAMETER GracefulTimeout
        Timeout for graceful shutdown.
    
    .PARAMETER ForceTimeout
        Additional timeout before forcing kill.
    
    .RETURNS
        Hashtable with termination details.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$ContainerMetadata,
        
        [Parameter(Mandatory=$true)]
        [int]$GracefulTimeout,
        
        [Parameter(Mandatory=$true)]
        [int]$ForceTimeout
    )
    
    try {
        Write-Log "Processing container: $($ContainerMetadata.name)" "INFO"
        
        $containerTermination = @{
            container_id = $ContainerMetadata.id
            container_name = $ContainerMetadata.name
            image = $ContainerMetadata.image
            initial_status = $ContainerMetadata.status
            termination_started_at = Get-Date -Format "o"
            termination_completed_at = $null
            attempts = @()
            final_status = $null
            success = $false
            error = $null
        }
        
        # Attempt graceful shutdown
        $gracefulResult = Stop-ContainerGracefully `
            -ContainerId $ContainerMetadata.id `
            -ContainerName $ContainerMetadata.name `
            -Timeout $GracefulTimeout
        
        $containerTermination.attempts += $gracefulResult
        
        if ($gracefulResult.success) {
            $containerTermination.success = $true
            $containerTermination.final_status = "stopped"
            $terminationReport.summary.successfully_stopped++
        }
        else {
            # Graceful shutdown failed, wait before force kill
            Write-Log "Graceful shutdown failed, waiting ${ForceTimeout}s before force kill..." "WARNING"
            Start-Sleep -Seconds $ForceTimeout
            
            # Check if container is still running
            if (Test-ContainerRunning -ContainerId $ContainerMetadata.id) {
                # Attempt force kill
                $forceResult = Stop-ContainerForcefully `
                    -ContainerId $ContainerMetadata.id `
                    -ContainerName $ContainerMetadata.name
                
                $containerTermination.attempts += $forceResult
                
                if ($forceResult.success) {
                    $containerTermination.success = $true
                    $containerTermination.final_status = "killed"
                    $terminationReport.summary.successfully_stopped++
                }
                else {
                    $containerTermination.error = "Both graceful and forceful termination failed"
                    $containerTermination.final_status = "failed"
                    $terminationReport.summary.failed_to_stop++
                }
            }
            else {
                # Container stopped during wait period
                Write-Log "Container $($ContainerMetadata.name) stopped during wait period" "INFO"
                $containerTermination.success = $true
                $containerTermination.final_status = "stopped"
                $terminationReport.summary.successfully_stopped++
            }
        }
        
        $containerTermination.termination_completed_at = Get-Date -Format "o"
        
        # Update migration state if available
        if (Get-Command -Name Add-ProcessedContainer -ErrorAction SilentlyContinue) {
            if ($containerTermination.success) {
                Add-ProcessedContainer `
                    -StatePath $StatePath `
                    -ContainerName $ContainerMetadata.name `
                    -ContainerId $ContainerMetadata.id
            }
        }
        
        Write-Log "Container $($ContainerMetadata.name) termination completed (Success: $($containerTermination.success))" "INFO"
        
        return $containerTermination
    }
    catch {
        Write-Log "Error terminating container $($ContainerMetadata.name): $_" "ERROR"
        $terminationReport.summary.failed_to_stop++
        
        return @{
            container_id = $ContainerMetadata.id
            container_name = $ContainerMetadata.name
            image = $ContainerMetadata.image
            success = $false
            error = $_.Exception.Message
        }
    }
}

function Test-AllContainersStopped {
    <#
    .SYNOPSIS
        Verifies that all containers are stopped.
    
    .PARAMETER ContainerIds
        Array of container IDs to verify.
    
    .RETURNS
        Hashtable with verification results.
    #>
    param(
        [Parameter(Mandatory=$true)]
        [array]$ContainerIds
    )
    
    try {
        Write-Log "Verifying all containers are stopped..." "INFO"
        
        $verification = @{
            all_stopped = $true
            still_running = @()
            not_found = @()
            stopped = @()
        }
        
        foreach ($containerId in $ContainerIds) {
            if (Test-ContainerRunning -ContainerId $containerId) {
                Write-Log "Container $containerId is still running" "ERROR"
                $verification.all_stopped = $false
                $verification.still_running += $containerId
            }
            elseif (Test-ContainerExists -ContainerId $containerId) {
                Write-Log "Container $containerId is stopped" "INFO"
                $verification.stopped += $containerId
            }
            else {
                Write-Log "Container $containerId not found (may have been removed)" "INFO"
                $verification.not_found += $containerId
            }
        }
        
        if ($verification.all_stopped) {
            Write-Log "Verification passed: All containers are stopped" "INFO"
        }
        else {
            Write-Log "Verification failed: $($verification.still_running.Count) container(s) still running" "ERROR"
        }
        
        return $verification
    }
    catch {
        Write-Log "Error during verification: $_" "ERROR"
        return @{
            all_stopped = $false
            error = $_.Exception.Message
        }
    }
}

# Main execution
try {
    Write-Log "Starting Docker container termination..." "INFO"
    
    # Update migration state to ContainerTermination phase
    if (Get-Command -Name Set-MigrationPhase -ErrorAction SilentlyContinue) {
        try {
            Set-MigrationPhase -StatePath $StatePath -NewPhase "ContainerTermination"
        }
        catch {
            Write-Log "Could not update migration phase: $_" "WARNING"
        }
    }
    
    # Check if inventory file exists
    if (-not (Test-Path $InventoryPath)) {
        throw "Inventory file not found: $InventoryPath. Please run Get-DockerInventory.ps1 first."
    }
    
    # Load inventory
    Write-Log "Loading inventory from: $InventoryPath" "INFO"
    $inventory = Get-Content $InventoryPath -Raw | ConvertFrom-Json
    
    if ($inventory.containers.Count -eq 0) {
        Write-Log "No containers found in inventory" "WARNING"
        
        # Still mark as success since there's nothing to stop
        $terminationReport.completed_at = Get-Date -Format "o"
        $terminationReport.summary.verification_passed = $true
        
        return @{
            success = $true
            message = "No containers to stop"
            report = $terminationReport
        }
    }
    
    Write-Log "Found $($inventory.containers.Count) container(s) to terminate" "INFO"
    Write-Log "Graceful timeout: ${GracefulTimeout}s, Force timeout: ${ForceTimeout}s" "INFO"
    
    # Terminate each container
    $terminationReport.summary.total_containers = $inventory.containers.Count
    
    foreach ($container in $inventory.containers) {
        # Convert PSCustomObject to hashtable
        $containerHash = @{}
        $container.PSObject.Properties | ForEach-Object { $containerHash[$_.Name] = $_.Value }
        
        $containerTermination = Stop-Container `
            -ContainerMetadata $containerHash `
            -GracefulTimeout $GracefulTimeout `
            -ForceTimeout $ForceTimeout
        
        $terminationReport.containers += $containerTermination
    }
    
    $terminationReport.completed_at = Get-Date -Format "o"
    
    # Verify clean shutdown if requested
    if ($VerifyCleanShutdown) {
        Write-Log "Performing clean shutdown verification..." "INFO"
        
        $containerIds = $inventory.containers | ForEach-Object { $_.id }
        $verification = Test-AllContainersStopped -ContainerIds $containerIds
        
        $terminationReport.verification = $verification
        $terminationReport.summary.verification_passed = $verification.all_stopped
    }
    else {
        $terminationReport.summary.verification_passed = $true
    }
    
    # Save termination report
    $reportDir = Split-Path -Parent $InventoryPath
    $reportPath = Join-Path $reportDir "container-termination-report.json"
    Write-Log "Saving termination report to: $reportPath" "INFO"
    $terminationReport | ConvertTo-Json -Depth 10 | Out-File -FilePath $reportPath -Encoding UTF8
    
    # Display summary
    Write-Log "=== Termination Summary ===" "INFO"
    Write-Log "Total containers: $($terminationReport.summary.total_containers)" "INFO"
    Write-Log "Successfully stopped: $($terminationReport.summary.successfully_stopped)" "INFO"
    Write-Log "Failed to stop: $($terminationReport.summary.failed_to_stop)" "INFO"
    Write-Log "Forcefully killed: $($terminationReport.summary.forcefully_killed)" "INFO"
    Write-Log "Verification passed: $($terminationReport.summary.verification_passed)" "INFO"
    
    # Determine overall success
    $overallSuccess = ($terminationReport.summary.failed_to_stop -eq 0) -and $terminationReport.summary.verification_passed
    
    if ($overallSuccess) {
        Write-Log "Container termination completed successfully" "INFO"
        return @{
            success = $true
            report_path = $reportPath
            summary = $terminationReport.summary
        }
    }
    else {
        Write-Log "Container termination completed with errors" "ERROR"
        return @{
            success = $false
            report_path = $reportPath
            summary = $terminationReport.summary
            verification = $terminationReport.verification
        }
    }
}
catch {
    Write-Log "Fatal error during container termination: $_" "ERROR"
    Write-Log $_.ScriptStackTrace "ERROR"
    
    # Update migration state with error
    if (Get-Command -Name Set-MigrationError -ErrorAction SilentlyContinue) {
        try {
            Set-MigrationError -StatePath $StatePath -ErrorMessage "Container termination failed: $($_.Exception.Message)"
        }
        catch {
            Write-Log "Could not update migration state with error: $_" "WARNING"
        }
    }
    
    # Save partial report if possible
    try {
        $terminationReport.completed_at = Get-Date -Format "o"
        $terminationReport.error = $_.Exception.Message
        $reportDir = Split-Path -Parent $InventoryPath
        $reportPath = Join-Path $reportDir "container-termination-report-failed.json"
        $terminationReport | ConvertTo-Json -Depth 10 | Out-File -FilePath $reportPath -Encoding UTF8
        Write-Log "Partial report saved to: $reportPath" "INFO"
    }
    catch {
        Write-Log "Failed to save partial report: $_" "ERROR"
    }
    
    # Return error
    return @{
        success = $false
        error = $_.Exception.Message
        stack_trace = $_.ScriptStackTrace
    }
}
