#!/bin/bash
# ============================================================================
# MORDOMO PARALLEL EXECUTION SCRIPT
# Execute 4 Aider tasks simultaneously for GenesisObserver optimization
# ============================================================================

echo "🎩 MORDOMO - Parallel Aider Execution"
echo "=========================================="
echo ""
echo "4 independent tasks ready for parallel execution via Aider (FREE)"
echo "Cost model: 100% Use (trinity-large-preview:free)"
echo ""
echo "INSTRUCTIONS:"
echo "1. Open 4 terminal windows/tabs"
echo "2. Navigate to: C:\Users\Ryzen\Desktop\AIOS_CLAUDE\aios-core"
echo "3. Copy ONE command per terminal from below"
echo "4. Run all 4 simultaneously"
echo "5. Monitor completion in all terminals"
echo ""
echo "=========================================="
echo ""

# Check environment
if [ -z "$OPENROUTER_API_KEY" ]; then
    echo "⚠️  WARNING: OPENROUTER_API_KEY not set"
    echo "Set it before running Aider:"
    echo "   export OPENROUTER_API_KEY='your-api-key'"
    echo ""
fi

echo "✅ TERMINAL 1 - JEST NAMESPACE FIX"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "aider --model openrouter/arcee-ai/trinity-large-preview:free \\"
echo "      --no-auto-commits \\"
echo "      --yes \\"
echo "      --file jest.config.js \\"
echo "      --file tsconfig.json \\"
echo "      --message \"Fix Jest namespace collision by ignoring AIDER-AIOS subdirectory. Update testPathIgnorePatterns in jest.config.js to exclude AIDER-AIOS from test discovery. Verify configuration prevents haste-map warnings. Ensure all existing tests still pass.\""
echo ""
echo "✅ Expected output:"
echo "   - jest.config.js updated with testPathIgnorePatterns"
echo "   - No haste-map warnings in test runs"
echo "   - All tests pass"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "✅ TERMINAL 2 - AIDER-FIRST UNIVERSALIZATION"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "aider --model openrouter/arcee-ai/trinity-large-preview:free \\"
echo "      --no-auto-commits \\"
echo "      --yes \\"
echo "      --file squads/dev-aider/README.md \\"
echo "      --file squads/games-squad/squad.yaml \\"
echo "      --file squads/marketing-squad/squad.yaml \\"
echo "      --file squads/dropshipping/squad.yaml \\"
echo "      --file squads/social-media-squad/squad.yaml \\"
echo "      --message \"Create comprehensive Aider-First universalization strategy. Analyze current cost model for all 13 squads. For each squad (games, marketing, dropshipping, social-media, etl, software-inc), document: current costs, proposed Aider-First approach, estimated savings (80-100%), conversion timeline, dependencies. Create new file: squads/AIDER-FIRST-STRATEGY.md with detailed conversion roadmap. Include cost comparison matrix and risk assessment.\""
echo ""
echo "✅ Expected output:"
echo "   - squads/AIDER-FIRST-STRATEGY.md created"
echo "   - Cost analysis per squad documented"
echo "   - Conversion timeline with milestones"
echo "   - 80-100% savings projections"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "✅ TERMINAL 3 - SPEC PIPELINE PREPARATION"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "aider --model openrouter/arcee-ai/trinity-large-preview:free \\"
echo "      --no-auto-commits \\"
echo "      --yes \\"
echo "      --file .aios-core/core-config.yaml \\"
echo "      --file .aios-core/constitution.md \\"
echo "      --message \"Prepare spec pipeline for Fase 3 activation (autoClaude.specPipeline). Create two new task files: (1) .aios-core/development/tasks/spec-generate-prd.md - generates PRD from story acceptance criteria via Aider, (2) .aios-core/development/tasks/spec-generate-architecture.md - generates architecture from PRD. Create docs/specifications/spec-pipeline-guide.md documenting: workflow, validation gates, integration with story system, configuration steps, example outputs.\""
echo ""
echo "✅ Expected output:"
echo "   - spec-generate-prd.md task template created"
echo "   - spec-generate-architecture.md task template created"
echo "   - spec-pipeline-guide.md documentation created"
echo "   - Ready for Fase 3 activation"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "✅ TERMINAL 4 - MULTI-DOMAIN EXPANSION ROADMAP"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "aider --model openrouter/arcee-ai/trinity-large-preview:free \\"
echo "      --no-auto-commits \\"
echo "      --yes \\"
echo "      --file squads/ \\"
echo "      --file docs/ \\"
echo "      --message \"Create multi-domain expansion roadmap for AIOS beyond software development. Analyze 5 strategic domains: (1) Education - learning management & curriculum, (2) Healthcare - patient records & diagnostics, (3) Creative Services - content & design, (4) Business Strategy - competitive analysis & planning, (5) Wellness - health coaching. For each domain: define squad composition, required agents, specialized tasks. Create reusable squads/templates/domain-squad-template.yaml. Develop docs/strategy/MULTI-DOMAIN-EXPANSION.md with vision, timeline (Q1-Q4 2026), resource estimates, risk assessment, success metrics.\""
echo ""
echo "✅ Expected output:"
echo "   - MULTI-DOMAIN-EXPANSION.md strategy document"
echo "   - domain-squad-template.yaml reusable template"
echo "   - 5 domain strategies detailed"
echo "   - Q1-Q4 2026 rollout timeline"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🚀 EXECUTION PLAN"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "STEP 1: Open 4 terminal windows (or tabs)"
echo "STEP 2: In each terminal, navigate to:"
echo "        cd /c/Users/Ryzen/Desktop/AIOS_CLAUDE/aios-core"
echo ""
echo "STEP 3: Copy and paste ONE command per terminal:"
echo "        Terminal 1 → JEST FIX command (above)"
echo "        Terminal 2 → AIDER-FIRST UNIVERSALIZATION command"
echo "        Terminal 3 → SPEC PIPELINE PREPARATION command"
echo "        Terminal 4 → MULTI-DOMAIN EXPANSION command"
echo ""
echo "STEP 4: Press ENTER in all 4 terminals (start simultaneously)"
echo ""
echo "STEP 5: Monitor all terminals"
echo "        - Aider will modify files automatically"
echo "        - No manual commits (--no-auto-commits flag)"
echo "        - Each task is independent (parallel-safe)"
echo ""
echo "STEP 6: After all 4 complete:"
echo "        - Review generated files"
echo "        - Run: npm run lint && npm run typecheck"
echo "        - Run: npm test"
echo "        - Create commit with all changes"
echo ""
echo "📊 ESTIMATED EXECUTION TIME"
echo "        Task 1 (Jest):        5-10 minutes"
echo "        Task 2 (Aider-First): 10-15 minutes"
echo "        Task 3 (Spec Pipe):   10-15 minutes"
echo "        Task 4 (Multi-Domain):10-15 minutes"
echo ""
echo "        All in parallel:      ~15-20 minutes total (vs 45-55 sequential)"
echo "        TIME SAVED:           ~30 minutes"
echo ""
echo "💰 COST ANALYSIS"
echo "        All 4 tasks via Aider: Use (FREE - trinity-large-preview:free)"
echo "        Cost if via Claude:    ~$0.50-1.00"
echo "        SAVINGS:               100% (Use instead of $$)"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Ready to execute! Copy commands above and run in 4 terminals."
echo ""
